import { TagData } from './types';

export const tagsData: TagData[] = [
  // ==================== MARKET & INDICES ====================
  { name: 'Stock Market', slug: 'stock-market', description: 'Stock market news, trends, and analysis', tagGroupSlug: 'market-indices', similarTagSlugs: ['equity-market', 'share-market'], relatedTagSlugs: ['sensex', 'nifty-50', 'bse', 'nse'] },
  { name: 'Sensex', slug: 'sensex', description: 'BSE Sensex index updates and analysis', tagGroupSlug: 'market-indices', similarTagSlugs: ['bse-sensex', 'sensex-30'], relatedTagSlugs: ['bse', 'nifty-50', 'stock-market'] },
  { name: 'Nifty 50', slug: 'nifty-50', description: 'NSE Nifty 50 index updates and analysis', tagGroupSlug: 'market-indices', similarTagSlugs: ['nifty', 'nifty-index'], relatedTagSlugs: ['nse', 'sensex', 'stock-market'] },
  { name: 'Nifty Bank', slug: 'nifty-bank', description: 'Nifty Bank index for banking sector', tagGroupSlug: 'market-indices', similarTagSlugs: ['bank-nifty'], relatedTagSlugs: ['banking-sector', 'hdfc-bank', 'icici-bank', 'sbi'] },
  { name: 'Nifty IT', slug: 'nifty-it', description: 'Nifty IT index for technology sector', tagGroupSlug: 'market-indices', relatedTagSlugs: ['it-sector', 'tcs', 'infosys', 'wipro'] },
  { name: 'Nifty Pharma', slug: 'nifty-pharma', description: 'Nifty Pharma index updates', tagGroupSlug: 'market-indices', relatedTagSlugs: ['pharma-sector', 'sun-pharma', 'dr-reddys', 'cipla'] },
  { name: 'Nifty Auto', slug: 'nifty-auto', description: 'Nifty Auto index for automobile sector', tagGroupSlug: 'market-indices', relatedTagSlugs: ['auto-sector', 'tata-motors', 'maruti-suzuki', 'mahindra'] },
  { name: 'Nifty FMCG', slug: 'nifty-fmcg', description: 'Nifty FMCG index updates', tagGroupSlug: 'market-indices', relatedTagSlugs: ['fmcg-sector', 'hindustan-unilever', 'itc', 'asian-paints'] },
  { name: 'Nifty Metal', slug: 'nifty-metal', description: 'Nifty Metal index for metals sector', tagGroupSlug: 'market-indices', relatedTagSlugs: ['metal-sector', 'tata-steel'] },
  { name: 'Nifty Realty', slug: 'nifty-realty', description: 'Nifty Realty index for real estate', tagGroupSlug: 'market-indices', relatedTagSlugs: ['real-estate'] },
  { name: 'Nifty Energy', slug: 'nifty-energy', description: 'Nifty Energy index updates', tagGroupSlug: 'market-indices', relatedTagSlugs: ['energy-sector', 'ongc', 'ntpc', 'power-grid'] },
  { name: 'Nifty PSU Bank', slug: 'nifty-psu-bank', description: 'Nifty PSU Bank index', tagGroupSlug: 'market-indices', relatedTagSlugs: ['psu-banks', 'sbi'] },
  { name: 'Nifty Midcap', slug: 'nifty-midcap', description: 'Nifty Midcap index for mid-sized companies', tagGroupSlug: 'market-indices', similarTagSlugs: ['midcap-stocks', 'midcap-index'], relatedTagSlugs: ['nifty-smallcap'] },
  { name: 'Nifty Smallcap', slug: 'nifty-smallcap', description: 'Nifty Smallcap index updates', tagGroupSlug: 'market-indices', similarTagSlugs: ['smallcap-stocks', 'smallcap-index'], relatedTagSlugs: ['nifty-midcap', 'penny-stocks'] },
  { name: 'BSE', slug: 'bse', description: 'Bombay Stock Exchange news', tagGroupSlug: 'market-indices', similarTagSlugs: ['bombay-stock-exchange'], relatedTagSlugs: ['sensex', 'nse', 'stock-market'] },
  { name: 'NSE', slug: 'nse', description: 'National Stock Exchange updates', tagGroupSlug: 'market-indices', similarTagSlugs: ['national-stock-exchange'], relatedTagSlugs: ['nifty-50', 'bse', 'stock-market'] },
  
  // ==================== MARKET TRENDS ====================
  { name: 'Bull Market', slug: 'bull-market', description: 'Bull market trends and opportunities', tagGroupSlug: 'market-trends', relatedTagSlugs: ['market-rally', 'all-time-high', 'stock-market'] },
  { name: 'Bear Market', slug: 'bear-market', description: 'Bear market analysis and strategies', tagGroupSlug: 'market-trends', relatedTagSlugs: ['market-correction', 'market-crash', 'volatility'] },
  { name: 'Market Rally', slug: 'market-rally', description: 'Stock market rally updates', tagGroupSlug: 'market-trends', relatedTagSlugs: ['bull-market', 'all-time-high'] },
  { name: 'Market Correction', slug: 'market-correction', description: 'Market correction analysis', tagGroupSlug: 'market-trends', relatedTagSlugs: ['bear-market', 'volatility', '52-week-low'] },
  { name: 'Market Crash', slug: 'market-crash', description: 'Market crash news and analysis', tagGroupSlug: 'market-trends', relatedTagSlugs: ['bear-market', 'volatility', 'market-correction'] },
  { name: 'Volatility', slug: 'volatility', description: 'Market volatility and VIX updates', tagGroupSlug: 'market-trends', similarTagSlugs: ['vix', 'india-vix'], relatedTagSlugs: ['options-trading', 'fno'] },
  { name: 'All-Time High', slug: 'all-time-high', description: 'Stocks hitting all-time highs', tagGroupSlug: 'market-trends', similarTagSlugs: ['ath', 'record-high'], relatedTagSlugs: ['bull-market', '52-week-high'] },
  { name: '52-Week High', slug: '52-week-high', description: 'Stocks at 52-week highs', tagGroupSlug: 'market-trends', relatedTagSlugs: ['all-time-high', 'bull-market'] },
  { name: '52-Week Low', slug: '52-week-low', description: 'Stocks at 52-week lows', tagGroupSlug: 'market-trends', relatedTagSlugs: ['bear-market', 'market-correction'] },
  
  // ==================== INVESTMENT PRODUCTS ====================
  { name: 'IPO', slug: 'ipo', description: 'Initial Public Offerings news and analysis', tagGroupSlug: 'investment-products', similarTagSlugs: ['initial-public-offering', 'new-listings'], relatedTagSlugs: ['sebi', 'stock-market'] },
  { name: 'Mutual Funds', slug: 'mutual-funds', description: 'Mutual fund investments and strategies', tagGroupSlug: 'investment-products', similarTagSlugs: ['mf', 'fund-investments'], relatedTagSlugs: ['sip', 'equity-funds', 'debt-funds', 'elss'] },
  { name: 'ETF', slug: 'etf', description: 'Exchange Traded Funds information', tagGroupSlug: 'investment-products', similarTagSlugs: ['exchange-traded-funds'], relatedTagSlugs: ['index-funds', 'mutual-funds', 'nifty-50'] },
  { name: 'SIP', slug: 'sip', description: 'Systematic Investment Plan updates', tagGroupSlug: 'investment-products', similarTagSlugs: ['systematic-investment-plan'], relatedTagSlugs: ['mutual-funds', 'equity-funds', 'elss'] },
  { name: 'Index Funds', slug: 'index-funds', description: 'Index fund investing', tagGroupSlug: 'investment-products', relatedTagSlugs: ['etf', 'mutual-funds', 'nifty-50', 'sensex'] },
  { name: 'Equity Funds', slug: 'equity-funds', description: 'Equity mutual fund updates', tagGroupSlug: 'investment-products', relatedTagSlugs: ['mutual-funds', 'sip', 'elss'] },
  { name: 'Debt Funds', slug: 'debt-funds', description: 'Debt mutual fund news', tagGroupSlug: 'investment-products', relatedTagSlugs: ['mutual-funds', 'bonds', 'fixed-deposit'] },
  { name: 'ELSS', slug: 'elss', description: 'Equity Linked Savings Scheme', tagGroupSlug: 'investment-products', similarTagSlugs: ['tax-saving-funds'], relatedTagSlugs: ['mutual-funds', 'tax-saving', 'section-80c'] },
  { name: 'Fixed Deposit', slug: 'fixed-deposit', description: 'Fixed deposit rates and comparisons', tagGroupSlug: 'investment-products', similarTagSlugs: ['fd', 'term-deposit'], relatedTagSlugs: ['interest-rates', 'banking', 'recurring-deposit'] },
  { name: 'Recurring Deposit', slug: 'recurring-deposit', description: 'RD rates and options', tagGroupSlug: 'investment-products', similarTagSlugs: ['rd'], relatedTagSlugs: ['fixed-deposit', 'banking'] },
  { name: 'PPF', slug: 'ppf', description: 'Public Provident Fund updates', tagGroupSlug: 'investment-products', similarTagSlugs: ['public-provident-fund'], relatedTagSlugs: ['tax-saving', 'section-80c', 'nps'] },
  { name: 'NPS', slug: 'nps', description: 'National Pension System news', tagGroupSlug: 'investment-products', similarTagSlugs: ['national-pension-system'], relatedTagSlugs: ['retirement', 'ppf', 'tax-saving'] },
  { name: 'Gold', slug: 'gold', description: 'Gold investment and price updates', tagGroupSlug: 'investment-products', similarTagSlugs: ['gold-prices', 'gold-investment'], relatedTagSlugs: ['silver', 'sovereign-gold-bond'] },
  { name: 'Silver', slug: 'silver', description: 'Silver prices and investment', tagGroupSlug: 'investment-products', relatedTagSlugs: ['gold', 'commodities'] },
  { name: 'Sovereign Gold Bond', slug: 'sovereign-gold-bond', description: 'SGB investment updates', tagGroupSlug: 'investment-products', similarTagSlugs: ['sgb'], relatedTagSlugs: ['gold', 'rbi', 'government-securities'] },
  { name: 'Real Estate', slug: 'real-estate', description: 'Real estate investment insights', tagGroupSlug: 'investment-products', similarTagSlugs: ['property', 'housing'], relatedTagSlugs: ['reits', 'home-loan', 'nifty-realty'] },
  { name: 'REITs', slug: 'reits', description: 'Real Estate Investment Trusts', tagGroupSlug: 'investment-products', similarTagSlugs: ['real-estate-investment-trusts'], relatedTagSlugs: ['real-estate'] },
  { name: 'Bonds', slug: 'bonds', description: 'Bond market and fixed income investments', tagGroupSlug: 'investment-products', relatedTagSlugs: ['government-securities', 'corporate-bonds', 'debt-funds'] },
  { name: 'Government Securities', slug: 'government-securities', description: 'G-Sec and treasury bonds', tagGroupSlug: 'investment-products', similarTagSlugs: ['g-sec', 'treasury-bonds'], relatedTagSlugs: ['bonds', 'rbi'] },
  { name: 'Corporate Bonds', slug: 'corporate-bonds', description: 'Corporate bond investments', tagGroupSlug: 'investment-products', relatedTagSlugs: ['bonds', 'debt-funds'] },
  { name: 'Cryptocurrency', slug: 'cryptocurrency', description: 'Cryptocurrency news and analysis', tagGroupSlug: 'investment-products', similarTagSlugs: ['crypto', 'digital-currency'], relatedTagSlugs: ['bitcoin', 'ethereum'] },
  { name: 'Bitcoin', slug: 'bitcoin', description: 'Bitcoin price and updates', tagGroupSlug: 'investment-products', similarTagSlugs: ['btc'], relatedTagSlugs: ['cryptocurrency', 'ethereum'] },
  { name: 'Ethereum', slug: 'ethereum', description: 'Ethereum news and analysis', tagGroupSlug: 'investment-products', similarTagSlugs: ['eth'], relatedTagSlugs: ['cryptocurrency', 'bitcoin'] },
  
  // ==================== BANKING & RBI ====================
  { name: 'RBI', slug: 'rbi', description: 'Reserve Bank of India policies and updates', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['reserve-bank-of-india'], relatedTagSlugs: ['repo-rate', 'monetary-policy', 'inflation', 'interest-rates'] },
  { name: 'Interest Rates', slug: 'interest-rates', description: 'Interest rate changes and impact', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['rbi', 'repo-rate', 'fixed-deposit', 'home-loan'] },
  { name: 'Repo Rate', slug: 'repo-rate', description: 'RBI repo rate updates', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['rbi', 'interest-rates', 'monetary-policy'] },
  { name: 'Inflation', slug: 'inflation', description: 'Inflation data and impact', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['cpi', 'wpi', 'rbi', 'interest-rates'] },
  { name: 'CPI', slug: 'cpi', description: 'Consumer Price Index updates', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['consumer-price-index'], relatedTagSlugs: ['inflation', 'wpi'] },
  { name: 'WPI', slug: 'wpi', description: 'Wholesale Price Index news', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['wholesale-price-index'], relatedTagSlugs: ['inflation', 'cpi'] },
  { name: 'Banking', slug: 'banking', description: 'Banking sector news and updates', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['psu-banks', 'private-banks', 'nbfcs', 'nifty-bank'] },
  { name: 'PSU Banks', slug: 'psu-banks', description: 'Public sector bank news', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['public-sector-banks'], relatedTagSlugs: ['sbi', 'banking', 'nifty-psu-bank'] },
  { name: 'Private Banks', slug: 'private-banks', description: 'Private banking sector updates', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['hdfc-bank', 'icici-bank', 'kotak-bank', 'banking'] },
  { name: 'NBFCs', slug: 'nbfcs', description: 'Non-Banking Financial Companies', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['non-banking-financial-companies'], relatedTagSlugs: ['bajaj-finance', 'banking'] },
  { name: 'Fintech', slug: 'fintech', description: 'Financial technology updates', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['financial-technology'], relatedTagSlugs: ['upi', 'digital-payments', 'paytm'] },
  { name: 'UPI', slug: 'upi', description: 'Unified Payments Interface news', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['unified-payments-interface'], relatedTagSlugs: ['digital-payments', 'fintech'] },
  { name: 'Digital Payments', slug: 'digital-payments', description: 'Digital payment trends', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['upi', 'fintech', 'credit-cards'] },
  { name: 'Credit Cards', slug: 'credit-cards', description: 'Credit card news and offers', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['banking', 'digital-payments', 'personal-loan'] },
  { name: 'Loans', slug: 'loans', description: 'Loan rates and options', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['home-loan', 'personal-loan', 'interest-rates'] },
  { name: 'Home Loan', slug: 'home-loan', description: 'Home loan rates and tips', tagGroupSlug: 'banking-rbi', similarTagSlugs: ['housing-loan', 'mortgage'], relatedTagSlugs: ['loans', 'real-estate', 'interest-rates'] },
  { name: 'Personal Loan', slug: 'personal-loan', description: 'Personal loan updates', tagGroupSlug: 'banking-rbi', relatedTagSlugs: ['loans', 'credit-cards', 'banking'] },
  
  // ==================== REGULATORS & INSURANCE ====================
  { name: 'SEBI', slug: 'sebi', description: 'Securities and Exchange Board regulations', tagGroupSlug: 'regulators-insurance', similarTagSlugs: ['securities-exchange-board'], relatedTagSlugs: ['ipo', 'stock-market', 'mutual-funds'] },
  { name: 'IRDAI', slug: 'irdai', description: 'Insurance regulator updates', tagGroupSlug: 'regulators-insurance', relatedTagSlugs: ['insurance', 'life-insurance', 'health-insurance'] },
  { name: 'PFRDA', slug: 'pfrda', description: 'Pension fund regulator news', tagGroupSlug: 'regulators-insurance', relatedTagSlugs: ['nps', 'retirement'] },
  { name: 'Insurance', slug: 'insurance', description: 'Insurance products and policies', tagGroupSlug: 'regulators-insurance', relatedTagSlugs: ['life-insurance', 'health-insurance', 'term-insurance', 'irdai'] },
  { name: 'Life Insurance', slug: 'life-insurance', description: 'Life insurance updates', tagGroupSlug: 'regulators-insurance', relatedTagSlugs: ['insurance', 'term-insurance', 'lic'] },
  { name: 'Health Insurance', slug: 'health-insurance', description: 'Health insurance news', tagGroupSlug: 'regulators-insurance', relatedTagSlugs: ['insurance', 'section-80d'] },
  { name: 'Term Insurance', slug: 'term-insurance', description: 'Term insurance plans', tagGroupSlug: 'regulators-insurance', relatedTagSlugs: ['life-insurance', 'insurance'] },
  
  // ==================== TAX & PERSONAL FINANCE ====================
  { name: 'Income Tax', slug: 'income-tax', description: 'Income tax rules and planning', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['itr-filing', 'tax-saving', 'section-80c', 'capital-gains'] },
  { name: 'ITR Filing', slug: 'itr-filing', description: 'Income tax return filing tips', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['income-tax-return'], relatedTagSlugs: ['income-tax', 'tax-saving'] },
  { name: 'GST', slug: 'gst', description: 'Goods and Services Tax updates', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['goods-services-tax'], relatedTagSlugs: ['budget', 'economy'] },
  { name: 'Tax Saving', slug: 'tax-saving', description: 'Tax saving tips and investments', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['section-80c', 'elss', 'ppf', 'income-tax'] },
  { name: 'Section 80C', slug: 'section-80c', description: 'Section 80C deductions', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['tax-saving', 'elss', 'ppf', 'life-insurance'] },
  { name: 'Section 80D', slug: 'section-80d', description: 'Section 80D health insurance deduction', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['tax-saving', 'health-insurance'] },
  { name: 'HRA', slug: 'hra', description: 'House Rent Allowance exemption', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['house-rent-allowance'], relatedTagSlugs: ['income-tax', 'tax-saving'] },
  { name: 'Capital Gains', slug: 'capital-gains', description: 'Capital gains tax updates', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['ltcg', 'stcg', 'income-tax', 'stock-market'] },
  { name: 'LTCG', slug: 'ltcg', description: 'Long Term Capital Gains tax', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['long-term-capital-gains'], relatedTagSlugs: ['capital-gains', 'stcg', 'equity-funds'] },
  { name: 'STCG', slug: 'stcg', description: 'Short Term Capital Gains tax', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['short-term-capital-gains'], relatedTagSlugs: ['capital-gains', 'ltcg'] },
  { name: 'Budget', slug: 'budget', description: 'Union and state budget analysis', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['union-budget', 'income-tax', 'gst', 'fiscal-policy'] },
  { name: 'Union Budget', slug: 'union-budget', description: 'Annual Union Budget coverage', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['india-budget', 'annual-budget'], relatedTagSlugs: ['budget', 'income-tax', 'gst'] },
  { name: 'Personal Finance', slug: 'personal-finance', description: 'Personal finance tips and planning', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['financial-planning', 'wealth-management', 'retirement'] },
  { name: 'Retirement', slug: 'retirement', description: 'Retirement planning and pension', tagGroupSlug: 'tax-personal-finance', similarTagSlugs: ['retirement-planning'], relatedTagSlugs: ['nps', 'ppf', 'personal-finance'] },
  { name: 'Financial Planning', slug: 'financial-planning', description: 'Comprehensive financial planning', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['personal-finance', 'wealth-management'] },
  { name: 'Wealth Management', slug: 'wealth-management', description: 'Wealth management strategies', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['personal-finance', 'financial-planning'] },
  { name: 'Emergency Fund', slug: 'emergency-fund', description: 'Building emergency funds', tagGroupSlug: 'tax-personal-finance', relatedTagSlugs: ['personal-finance', 'fixed-deposit'] },
  
  // ==================== SECTORS ====================
  { name: 'IT Sector', slug: 'it-sector', description: 'Information Technology sector news', tagGroupSlug: 'sectors', similarTagSlugs: ['technology-sector', 'software-sector'], relatedTagSlugs: ['nifty-it', 'tcs', 'infosys', 'wipro', 'hcl-tech'] },
  { name: 'Banking Sector', slug: 'banking-sector', description: 'Banking and financial services sector', tagGroupSlug: 'sectors', relatedTagSlugs: ['nifty-bank', 'banking', 'hdfc-bank', 'icici-bank', 'sbi'] },
  { name: 'Pharma Sector', slug: 'pharma-sector', description: 'Pharmaceutical sector updates', tagGroupSlug: 'sectors', similarTagSlugs: ['healthcare-sector'], relatedTagSlugs: ['nifty-pharma', 'sun-pharma', 'dr-reddys', 'cipla'] },
  { name: 'Auto Sector', slug: 'auto-sector', description: 'Automobile sector news', tagGroupSlug: 'sectors', similarTagSlugs: ['automobile-sector'], relatedTagSlugs: ['nifty-auto', 'tata-motors', 'maruti-suzuki', 'mahindra', 'electric-vehicles'] },
  { name: 'Energy Sector', slug: 'energy-sector', description: 'Energy and power sector', tagGroupSlug: 'sectors', similarTagSlugs: ['power-sector'], relatedTagSlugs: ['nifty-energy', 'ongc', 'ntpc', 'power-grid', 'renewable-energy'] },
  { name: 'FMCG Sector', slug: 'fmcg-sector', description: 'Fast Moving Consumer Goods sector', tagGroupSlug: 'sectors', relatedTagSlugs: ['nifty-fmcg', 'hindustan-unilever', 'itc', 'asian-paints'] },
  { name: 'Telecom Sector', slug: 'telecom-sector', description: 'Telecommunications sector', tagGroupSlug: 'sectors', relatedTagSlugs: ['bharti-airtel', 'jio'] },
  { name: 'Infrastructure', slug: 'infrastructure', description: 'Infrastructure and construction sector', tagGroupSlug: 'sectors', similarTagSlugs: ['infra-sector'], relatedTagSlugs: ['cement', 'real-estate'] },
  { name: 'Metal Sector', slug: 'metal-sector', description: 'Metals and mining sector', tagGroupSlug: 'sectors', relatedTagSlugs: ['nifty-metal', 'tata-steel'] },
  { name: 'Cement', slug: 'cement', description: 'Cement industry updates', tagGroupSlug: 'sectors', relatedTagSlugs: ['infrastructure', 'real-estate'] },
  { name: 'Oil & Gas', slug: 'oil-gas', description: 'Oil and gas sector news', tagGroupSlug: 'sectors', relatedTagSlugs: ['ongc', 'bpcl', 'ioc', 'crude-oil'] },
  { name: 'Renewable Energy', slug: 'renewable-energy', description: 'Solar, wind, and green energy', tagGroupSlug: 'sectors', similarTagSlugs: ['green-energy', 'clean-energy'], relatedTagSlugs: ['energy-sector', 'electric-vehicles'] },
  { name: 'Electric Vehicles', slug: 'electric-vehicles', description: 'EV sector updates', tagGroupSlug: 'sectors', similarTagSlugs: ['ev', 'ev-sector'], relatedTagSlugs: ['auto-sector', 'tata-motors', 'renewable-energy'] },
  { name: 'Defence Sector', slug: 'defence-sector', description: 'Defence and aerospace sector', tagGroupSlug: 'sectors', relatedTagSlugs: ['make-in-india'] },
  { name: 'Chemicals', slug: 'chemicals', description: 'Chemical industry news', tagGroupSlug: 'sectors', similarTagSlugs: ['chemical-sector'] },
  { name: 'Textiles', slug: 'textiles', description: 'Textile industry updates', tagGroupSlug: 'sectors', similarTagSlugs: ['textile-sector'] },
  { name: 'Hospitality', slug: 'hospitality', description: 'Hotels and tourism sector', tagGroupSlug: 'sectors', similarTagSlugs: ['tourism-sector', 'hotel-sector'] },
  { name: 'Aviation', slug: 'aviation', description: 'Airlines and aviation sector', tagGroupSlug: 'sectors', similarTagSlugs: ['airlines-sector'] },
  { name: 'Railways', slug: 'railways', description: 'Railway sector news', tagGroupSlug: 'sectors', similarTagSlugs: ['indian-railways'] },
  { name: 'E-commerce', slug: 'e-commerce', description: 'Online retail and e-commerce', tagGroupSlug: 'sectors', similarTagSlugs: ['online-retail'], relatedTagSlugs: ['zomato'] },
  
  // ==================== MAJOR COMPANIES ====================
  { name: 'Reliance Industries', slug: 'reliance-industries', description: 'Reliance Industries news', tagGroupSlug: 'major-companies', similarTagSlugs: ['reliance', 'ril'], relatedTagSlugs: ['jio', 'oil-gas', 'sensex'] },
  { name: 'TCS', slug: 'tcs', description: 'Tata Consultancy Services updates', tagGroupSlug: 'major-companies', similarTagSlugs: ['tata-consultancy-services'], relatedTagSlugs: ['it-sector', 'nifty-it', 'infosys'] },
  { name: 'HDFC Bank', slug: 'hdfc-bank', description: 'HDFC Bank news and analysis', tagGroupSlug: 'major-companies', relatedTagSlugs: ['banking-sector', 'nifty-bank', 'private-banks'] },
  { name: 'Infosys', slug: 'infosys', description: 'Infosys company news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['it-sector', 'nifty-it', 'tcs'] },
  { name: 'ICICI Bank', slug: 'icici-bank', description: 'ICICI Bank updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['banking-sector', 'nifty-bank', 'private-banks'] },
  { name: 'SBI', slug: 'sbi', description: 'State Bank of India news', tagGroupSlug: 'major-companies', similarTagSlugs: ['state-bank-of-india'], relatedTagSlugs: ['psu-banks', 'nifty-bank', 'banking-sector'] },
  { name: 'Tata Motors', slug: 'tata-motors', description: 'Tata Motors updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['auto-sector', 'nifty-auto', 'electric-vehicles'] },
  { name: 'Tata Steel', slug: 'tata-steel', description: 'Tata Steel news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['metal-sector', 'nifty-metal'] },
  { name: 'Wipro', slug: 'wipro', description: 'Wipro company updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['it-sector', 'nifty-it'] },
  { name: 'HCL Tech', slug: 'hcl-tech', description: 'HCL Technologies news', tagGroupSlug: 'major-companies', similarTagSlugs: ['hcl-technologies'], relatedTagSlugs: ['it-sector', 'nifty-it'] },
  { name: 'Bharti Airtel', slug: 'bharti-airtel', description: 'Airtel telecom news', tagGroupSlug: 'major-companies', similarTagSlugs: ['airtel'], relatedTagSlugs: ['telecom-sector', 'jio'] },
  { name: 'Jio', slug: 'jio', description: 'Reliance Jio updates', tagGroupSlug: 'major-companies', similarTagSlugs: ['reliance-jio'], relatedTagSlugs: ['reliance-industries', 'telecom-sector'] },
  { name: 'Adani Group', slug: 'adani-group', description: 'Adani Group news', tagGroupSlug: 'major-companies', similarTagSlugs: ['adani'], relatedTagSlugs: ['infrastructure', 'energy-sector'] },
  { name: 'Maruti Suzuki', slug: 'maruti-suzuki', description: 'Maruti Suzuki updates', tagGroupSlug: 'major-companies', similarTagSlugs: ['maruti'], relatedTagSlugs: ['auto-sector', 'nifty-auto'] },
  { name: 'Mahindra', slug: 'mahindra', description: 'Mahindra Group news', tagGroupSlug: 'major-companies', similarTagSlugs: ['mahindra-mahindra', 'mm'], relatedTagSlugs: ['auto-sector', 'electric-vehicles'] },
  { name: 'Bajaj Finance', slug: 'bajaj-finance', description: 'Bajaj Finance updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['nbfcs', 'banking-sector'] },
  { name: 'Kotak Bank', slug: 'kotak-bank', description: 'Kotak Mahindra Bank news', tagGroupSlug: 'major-companies', similarTagSlugs: ['kotak-mahindra-bank'], relatedTagSlugs: ['private-banks', 'nifty-bank'] },
  { name: 'Asian Paints', slug: 'asian-paints', description: 'Asian Paints company news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['fmcg-sector', 'nifty-fmcg'] },
  { name: 'ITC', slug: 'itc', description: 'ITC Limited updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['fmcg-sector', 'nifty-fmcg'] },
  { name: 'Hindustan Unilever', slug: 'hindustan-unilever', description: 'HUL company news', tagGroupSlug: 'major-companies', similarTagSlugs: ['hul'], relatedTagSlugs: ['fmcg-sector', 'nifty-fmcg'] },
  { name: 'Sun Pharma', slug: 'sun-pharma', description: 'Sun Pharmaceutical news', tagGroupSlug: 'major-companies', similarTagSlugs: ['sun-pharmaceutical'], relatedTagSlugs: ['pharma-sector', 'nifty-pharma'] },
  { name: 'Dr Reddys', slug: 'dr-reddys', description: 'Dr Reddys Laboratories updates', tagGroupSlug: 'major-companies', similarTagSlugs: ['dr-reddys-laboratories'], relatedTagSlugs: ['pharma-sector', 'nifty-pharma'] },
  { name: 'Cipla', slug: 'cipla', description: 'Cipla pharma news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['pharma-sector', 'nifty-pharma'] },
  { name: 'ONGC', slug: 'ongc', description: 'Oil and Natural Gas Corporation', tagGroupSlug: 'major-companies', relatedTagSlugs: ['oil-gas', 'energy-sector', 'nifty-energy'] },
  { name: 'NTPC', slug: 'ntpc', description: 'NTPC power sector news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['energy-sector', 'nifty-energy', 'power-grid'] },
  { name: 'Power Grid', slug: 'power-grid', description: 'Power Grid Corporation updates', tagGroupSlug: 'major-companies', similarTagSlugs: ['power-grid-corporation'], relatedTagSlugs: ['energy-sector', 'nifty-energy', 'ntpc'] },
  { name: 'Coal India', slug: 'coal-india', description: 'Coal India Limited news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['energy-sector', 'disinvestment'] },
  { name: 'BPCL', slug: 'bpcl', description: 'Bharat Petroleum updates', tagGroupSlug: 'major-companies', similarTagSlugs: ['bharat-petroleum'], relatedTagSlugs: ['oil-gas', 'ioc'] },
  { name: 'IOC', slug: 'ioc', description: 'Indian Oil Corporation news', tagGroupSlug: 'major-companies', similarTagSlugs: ['indian-oil'], relatedTagSlugs: ['oil-gas', 'bpcl'] },
  { name: 'LIC', slug: 'lic', description: 'Life Insurance Corporation updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['life-insurance', 'insurance', 'ipo'] },
  { name: 'Zomato', slug: 'zomato', description: 'Zomato food delivery updates', tagGroupSlug: 'major-companies', relatedTagSlugs: ['e-commerce', 'ipo'] },
  { name: 'Paytm', slug: 'paytm', description: 'Paytm fintech news', tagGroupSlug: 'major-companies', relatedTagSlugs: ['fintech', 'digital-payments'] },
  
  // ==================== GLOBAL MARKETS ====================
  { name: 'US Markets', slug: 'us-markets', description: 'US stock market updates', tagGroupSlug: 'global-markets', similarTagSlugs: ['wall-street', 'american-markets'], relatedTagSlugs: ['dow-jones', 'sp-500', 'nasdaq'] },
  { name: 'Dow Jones', slug: 'dow-jones', description: 'Dow Jones Industrial Average', tagGroupSlug: 'global-markets', similarTagSlugs: ['djia'], relatedTagSlugs: ['us-markets', 'sp-500', 'nasdaq'] },
  { name: 'S&P 500', slug: 'sp-500', description: 'S&P 500 index updates', tagGroupSlug: 'global-markets', relatedTagSlugs: ['us-markets', 'dow-jones', 'nasdaq'] },
  { name: 'NASDAQ', slug: 'nasdaq', description: 'NASDAQ index news', tagGroupSlug: 'global-markets', relatedTagSlugs: ['us-markets', 'dow-jones', 'sp-500'] },
  { name: 'Global Economy', slug: 'global-economy', description: 'Global economic trends', tagGroupSlug: 'global-markets', relatedTagSlugs: ['economy', 'fed', 'us-markets'] },
  { name: 'Crude Oil', slug: 'crude-oil', description: 'Crude oil prices and impact', tagGroupSlug: 'global-markets', similarTagSlugs: ['oil-prices'], relatedTagSlugs: ['brent-crude', 'oil-gas', 'ongc'] },
  { name: 'Brent Crude', slug: 'brent-crude', description: 'Brent crude oil prices', tagGroupSlug: 'global-markets', relatedTagSlugs: ['crude-oil', 'oil-gas'] },
  { name: 'Dollar', slug: 'dollar', description: 'USD/INR exchange rate', tagGroupSlug: 'global-markets', similarTagSlugs: ['usd', 'usd-inr'], relatedTagSlugs: ['rupee', 'forex-reserves'] },
  { name: 'Rupee', slug: 'rupee', description: 'Indian Rupee currency updates', tagGroupSlug: 'global-markets', similarTagSlugs: ['inr', 'indian-rupee'], relatedTagSlugs: ['dollar', 'rbi', 'forex-reserves'] },
  { name: 'Fed', slug: 'fed', description: 'US Federal Reserve updates', tagGroupSlug: 'global-markets', similarTagSlugs: ['federal-reserve', 'us-fed'], relatedTagSlugs: ['fed-rate', 'us-markets', 'global-economy'] },
  { name: 'Fed Rate', slug: 'fed-rate', description: 'Federal Reserve rate decisions', tagGroupSlug: 'global-markets', similarTagSlugs: ['federal-funds-rate'], relatedTagSlugs: ['fed', 'interest-rates', 'us-markets'] },
  { name: 'China Markets', slug: 'china-markets', description: 'Chinese market updates', tagGroupSlug: 'global-markets', relatedTagSlugs: ['asian-markets', 'global-economy'] },
  { name: 'Asian Markets', slug: 'asian-markets', description: 'Asian stock market news', tagGroupSlug: 'global-markets', relatedTagSlugs: ['china-markets', 'global-economy'] },
  { name: 'European Markets', slug: 'european-markets', description: 'European market updates', tagGroupSlug: 'global-markets', relatedTagSlugs: ['global-economy'] },
  { name: 'FII', slug: 'fii', description: 'Foreign Institutional Investors activity', tagGroupSlug: 'global-markets', similarTagSlugs: ['foreign-institutional-investors'], relatedTagSlugs: ['dii', 'fdi', 'stock-market'] },
  { name: 'DII', slug: 'dii', description: 'Domestic Institutional Investors activity', tagGroupSlug: 'global-markets', similarTagSlugs: ['domestic-institutional-investors'], relatedTagSlugs: ['fii', 'mutual-funds', 'stock-market'] },
  { name: 'FDI', slug: 'fdi', description: 'Foreign Direct Investment', tagGroupSlug: 'global-markets', similarTagSlugs: ['foreign-direct-investment'], relatedTagSlugs: ['fii', 'economy', 'make-in-india'] },
  
  // ==================== ANALYSIS & RESEARCH ====================
  { name: 'Technical Analysis', slug: 'technical-analysis', description: 'Technical chart analysis', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['fundamental-analysis', 'stock-picks', 'day-trading'] },
  { name: 'Fundamental Analysis', slug: 'fundamental-analysis', description: 'Fundamental company analysis', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['technical-analysis', 'quarterly-results', 'value-investing'] },
  { name: 'Stock Picks', slug: 'stock-picks', description: 'Stock recommendations', tagGroupSlug: 'analysis-research', similarTagSlugs: ['stock-recommendations'], relatedTagSlugs: ['expert-opinion', 'technical-analysis'] },
  { name: 'Expert Opinion', slug: 'expert-opinion', description: 'Expert views and recommendations', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['stock-picks', 'market-outlook'] },
  { name: 'Market Outlook', slug: 'market-outlook', description: 'Market predictions and outlook', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['expert-opinion', 'stock-market'] },
  { name: 'Quarterly Results', slug: 'quarterly-results', description: 'Company quarterly earnings', tagGroupSlug: 'analysis-research', similarTagSlugs: ['q1-results', 'q2-results', 'q3-results', 'q4-results'], relatedTagSlugs: ['earnings', 'annual-results', 'fundamental-analysis'] },
  { name: 'Annual Results', slug: 'annual-results', description: 'Company annual results', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['quarterly-results', 'earnings'] },
  { name: 'Earnings', slug: 'earnings', description: 'Company earnings updates', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['quarterly-results', 'annual-results'] },
  { name: 'Dividends', slug: 'dividends', description: 'Dividend announcements', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['earnings', 'value-investing'] },
  { name: 'Stock Split', slug: 'stock-split', description: 'Stock split news', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['bonus-shares', 'corporate-governance'] },
  { name: 'Bonus Shares', slug: 'bonus-shares', description: 'Bonus share announcements', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['stock-split', 'dividends'] },
  { name: 'Buyback', slug: 'buyback', description: 'Share buyback updates', tagGroupSlug: 'analysis-research', similarTagSlugs: ['share-buyback'], relatedTagSlugs: ['corporate-governance'] },
  { name: 'Mergers Acquisitions', slug: 'mergers-acquisitions', description: 'M&A deals and news', tagGroupSlug: 'analysis-research', similarTagSlugs: ['ma', 'm-and-a'], relatedTagSlugs: ['corporate-governance'] },
  { name: 'Corporate Governance', slug: 'corporate-governance', description: 'Corporate governance updates', tagGroupSlug: 'analysis-research', relatedTagSlugs: ['sebi', 'mergers-acquisitions'] },
  
  // ==================== TRADING ====================
  { name: 'Day Trading', slug: 'day-trading', description: 'Day trading strategies', tagGroupSlug: 'trading', relatedTagSlugs: ['intraday', 'technical-analysis', 'swing-trading'] },
  { name: 'Swing Trading', slug: 'swing-trading', description: 'Swing trading techniques', tagGroupSlug: 'trading', relatedTagSlugs: ['day-trading', 'technical-analysis'] },
  { name: 'Options Trading', slug: 'options-trading', description: 'Options and derivatives trading', tagGroupSlug: 'trading', relatedTagSlugs: ['fno', 'futures-trading', 'volatility'] },
  { name: 'Futures Trading', slug: 'futures-trading', description: 'Futures market trading', tagGroupSlug: 'trading', relatedTagSlugs: ['fno', 'options-trading'] },
  { name: 'F&O', slug: 'fno', description: 'Futures and Options updates', tagGroupSlug: 'trading', similarTagSlugs: ['futures-options'], relatedTagSlugs: ['options-trading', 'futures-trading', 'nifty-50'] },
  { name: 'Intraday', slug: 'intraday', description: 'Intraday trading tips', tagGroupSlug: 'trading', similarTagSlugs: ['intraday-trading'], relatedTagSlugs: ['day-trading', 'technical-analysis'] },
  { name: 'Delivery Trading', slug: 'delivery-trading', description: 'Long-term delivery trades', tagGroupSlug: 'trading', relatedTagSlugs: ['value-investing', 'blue-chip-stocks'] },
  { name: 'Penny Stocks', slug: 'penny-stocks', description: 'Penny stock updates', tagGroupSlug: 'trading', relatedTagSlugs: ['nifty-smallcap', 'multibagger'] },
  { name: 'Multibagger', slug: 'multibagger', description: 'Multibagger stock picks', tagGroupSlug: 'trading', relatedTagSlugs: ['penny-stocks', 'growth-investing'] },
  { name: 'Blue Chip Stocks', slug: 'blue-chip-stocks', description: 'Large cap blue chip stocks', tagGroupSlug: 'trading', similarTagSlugs: ['large-cap-stocks'], relatedTagSlugs: ['value-investing', 'sensex', 'nifty-50'] },
  { name: 'Value Investing', slug: 'value-investing', description: 'Value investing strategies', tagGroupSlug: 'trading', relatedTagSlugs: ['fundamental-analysis', 'blue-chip-stocks', 'dividends'] },
  { name: 'Growth Investing', slug: 'growth-investing', description: 'Growth stock investing', tagGroupSlug: 'trading', relatedTagSlugs: ['multibagger', 'equity-funds'] },
  
  // ==================== ECONOMY & POLICY ====================
  { name: 'GDP', slug: 'gdp', description: 'Gross Domestic Product updates', tagGroupSlug: 'economy-policy', similarTagSlugs: ['gross-domestic-product'], relatedTagSlugs: ['economy', 'global-economy'] },
  { name: 'Economy', slug: 'economy', description: 'Indian economy news', tagGroupSlug: 'economy-policy', similarTagSlugs: ['indian-economy'], relatedTagSlugs: ['gdp', 'fiscal-policy', 'monetary-policy'] },
  { name: 'Fiscal Policy', slug: 'fiscal-policy', description: 'Government fiscal policy', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['budget', 'economy', 'monetary-policy'] },
  { name: 'Monetary Policy', slug: 'monetary-policy', description: 'RBI monetary policy', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['rbi', 'repo-rate', 'interest-rates'] },
  { name: 'Make in India', slug: 'make-in-india', description: 'Make in India initiative', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['pli-scheme', 'fdi', 'economy'] },
  { name: 'PLI Scheme', slug: 'pli-scheme', description: 'Production Linked Incentive scheme', tagGroupSlug: 'economy-policy', similarTagSlugs: ['production-linked-incentive'], relatedTagSlugs: ['make-in-india', 'economy'] },
  { name: 'Disinvestment', slug: 'disinvestment', description: 'Government disinvestment', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['privatization', 'budget'] },
  { name: 'Privatization', slug: 'privatization', description: 'PSU privatization news', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['disinvestment', 'psu-banks'] },
  { name: 'Exports', slug: 'exports', description: 'Export trade updates', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['imports', 'trade-deficit', 'economy'] },
  { name: 'Imports', slug: 'imports', description: 'Import trade news', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['exports', 'trade-deficit'] },
  { name: 'Trade Deficit', slug: 'trade-deficit', description: 'Trade balance updates', tagGroupSlug: 'economy-policy', relatedTagSlugs: ['exports', 'imports', 'current-account'] },
  { name: 'Current Account', slug: 'current-account', description: 'Current account deficit', tagGroupSlug: 'economy-policy', similarTagSlugs: ['cad', 'current-account-deficit'], relatedTagSlugs: ['trade-deficit', 'forex-reserves'] },
  { name: 'Forex Reserves', slug: 'forex-reserves', description: 'Foreign exchange reserves', tagGroupSlug: 'economy-policy', similarTagSlugs: ['foreign-exchange-reserves'], relatedTagSlugs: ['rbi', 'dollar', 'rupee'] },
];
